<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.3.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\CloseBlack.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\CloseBlackIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\CloseWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\CloseWhiteIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MaximizeBlack.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MaximizeBlackIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MaximizeWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MaximizeWhiteIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MinimizeBlack.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MinimizeBlackIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MinimizeWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\MinimizeWhiteIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\RestoreBlack.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\RestoreBlackIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\RestoreWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\RestoreWhiteIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\MainWindow\MainView.axaml.cs">
      <DependentUpon>MainView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ProgressWindow\ProgressView.axaml.cs">
      <DependentUpon>ProgressView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ProgressWindow\ProgressWindow.axaml.cs">
      <DependentUpon>ProgressWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SearchWindow\GotoView.axaml.cs">
      <DependentUpon>GotoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SearchWindow\FindView.axaml.cs">
      <DependentUpon>FindView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SearchWindow\FindInFilesView.axaml.cs">
      <DependentUpon>FindInFilesView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SearchWindow\ReplaceView.axaml.cs">
      <DependentUpon>ReplaceView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SearchWindow\SearchWindow.axaml.cs">
      <DependentUpon>SearchWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
